apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  labels:
    app: feed-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
      - name: udagram-feed-microservice
        image: omara7med/udagram-feed-microservice
        ports:
        - containerPort: 80
