apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-feed-api-v0
  name: udagram-feed-api-v0
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-feed-api-v0